### ISSUE TITLE
Pre-built

### ISSUE THREAD

**Issue by ImControl** [gitnew2018/My-OpenPeriscope#1]
Hi Im not very good with all the different programs and setting them up ect. I have the problem with OpenPeriscope live recording being all choppy and timestamps wrong.

I was trying to get your version to work but am quite lost, is there a prebuilt any where or like a step by step guide lol, sorry and thanks for any info.

**Comment by gitnew2018** [comment]
Actually I was going to make it work on linux, before first release. Also I'm going to make a guide how to build it from source by your self.

**Comment by gitnew2018** [comment]
Guide is up [link](https://github.com/gitnew2018/My-OpenPeriscope/wiki).

**Comment by gitnew2018** [comment]
@ImControl check releases page. Hopefully everything works :sweat:
