### ISSUE TITLE
Show node periscopeDownloader links in settings

### ISSUE THREAD

**Issue by kewalsk** [gitnew2018/My-OpenPeriscope#15]
What was the reason to exclude setting "Show node periscopeDownloader links" from node version?

**Comment by KaMyKaSii** [comment]
I think he thought it would only be useful in the userscript version.
Take a look at the comments in [my issue] (https://github.com/gitnew2018/My-OpenPeriscope/issues/2)

**Comment by gitnew2018** [comment]
What @KaMyKaSii said.
PeriscopeDownloader is a standalone version of downloaderNode.js used in my my-openperiscope.
It is only needed for userscript version where you cannot use nodejs directly.
