### ISSUE TITLE
Private broadcasts not downloading

### ISSUE THREAD

**Issue by ImControl** [gitnew2018/My-OpenPeriscope#16]
I built using the updated files from 9hrs ago and I'm still unable to download private broadcasts. If Im doing something wrong would you be able to update the pre-built executable.

**Comment by gitnew2018** [comment]
This is what i get when i do last minute changes.
Cookie was missing `;` at the end.
I also added instructions to downloaderNode.js, how to debug without console.

**Comment by Kamouser** [comment]
Hi @gitnew2018 With the latest update some livestreams do not download me, ex: in the Download Manager section shows me 3 private, I check the folder and only 2 appears to me.
this happens because the streamer have bad connection ? or can it be an my-openperiscope error?

**Comment by gitnew2018** [comment]
It is absolutely possible it's error on my end. I usually test it for like 10mins before submitting to github.
Right now I'm working on downloading whole broadcast with one click, It might take a few days and then I will make sure that everything essential is working and if people notice any problems then don't be afraid to ask.

**Comment by Kamouser** [comment]
@gitnew I found a new bug with autodownload privates with specific users.. only processes the weight but not the duration
![bugg](https://user-images.githubusercontent.com/50481149/61487164-8f31fc00-a97b-11e9-98f3-ac179a19a0d8.JPG)
![bugg2](https://user-images.githubusercontent.com/50481149/61487162-8f31fc00-a97b-11e9-8555-0787e4ca5fc9.JPG)

**Comment by Kamouser** [comment]
I think the previous version (0.1.8) is working better than the current one...

**Comment by gitnew2018** [comment]
Try now.

**Comment by Kamouser** [comment]
ok testing..

**Comment by Kamouser** [comment]
> Try now, ver. 0.1.10.

the bug of duration continues in the new version(0.1.10) with specific users in autodownload privates
![bugg3](https://user-images.githubusercontent.com/50481149/61607647-1b674c00-ac26-11e9-961c-a61eaa3f3606.JPG)

**Comment by gitnew2018** [comment]
Ok, found the culprit, should be fixed.
ps. You might like MPC BE, it has nice previews in the timeline, similar to youtube and keyboard shortcuts to rotate video 90*.
