### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Halinks** [gitnew2018/My-OpenPeriscope#19]
Hey! I've stumbled upon My-OpenPeriscope and I'm a big fan! Great work so far!

I'm using the standalone application and there are a few things I don't understand:

- What does "Log in with SID" mean or do?
- Is it possible to copy m3u8 links of lives/replays and watch them in the player of your choice? For me it's not working.
- Would it be possible to log in with Google/Facebook in the future?
- Where is the userdata stored? Can you just copy paste it in your folder and the login information is restored?
- "You can download private broadcasts that were deleted (drkchange28)" Does that mean you need to get the stream link so you can download it? Or does it log the link somewhere automatically?

**Comment by gitnew2018** [comment]
When you are logged in, open console then click on the arrow near `ready!  Object` you will see `cookie` which is Session id. To login with it paste it without `""`.

I have never done that but i think it should work, maybe someone else can help you with that. As for private broadcasts, a player should somehow accept cookies.

I don't plan to add it but would accept pull request. @kewalsk said in his PR that you can use Google/Facebook SID (I don't know how to get it) to login.

In userdata folder😉. Yes, everything is restored when you copy whole folder. I'm not sure which files are necessary, if i had to guess i would say `userdata/Local Storage/app_openperiscope_0.localstorage`.

You need to enable `Show partial replay(PR) links` in settings.
The program attempts to grab replay link & decryption key at the end of a broadcast (shows as: ▼ | Copy R_URL). If broadcaster is fast and `Notifications refresh interval` is very long then chances of getting the link are small.
There is also possibility that some or all video chunks or playlist disappear from servers then the video won't download or download corrupted(missing chunks).

**Comment by Halinks** [comment]
Thanks for the detailed answer!

> The program attempts to grab replay link & decryption key at the end of a broadcast (shows as: ▼ | Copy R_URL). If broadcaster is fast and `Notifications refresh interval` is very long then chances of getting the link are small.

Can you lower the refresh interval below 15s? Would that be advisable or would it end in errors?

**Comment by gitnew2018** [comment]
You can, however from my experience, when setting it below 5s, periscope might decide to stop responding for few minutes.

**Comment by kewalsk** [comment]
@Halinks "Log in by SID" is not really login but reusing existing session. There are many ways to get sid. If you have rooted android device you can look for it in app config files. I suppose ios also needs JB to get them. However, the easiest way is just login to your account on PC in any web browser and take it from cookies. Remember that you cannot logout in web browser because this will invalidate the session. Better use private mode and just close the browser after getting the cookie. Any method of authentication can be used in web browser - twitter/google/fb/phone, so this is kind of workaround for implementation of different methods in OpenPeriscope.

**Comment by Halinks** [comment]
That's some valuable information! Thanks @kewalsk ! :)
Oh one more question @gitnew2018 ... 
Would you mind telling me which files are necessary for the standalone application and which aren't after you have built it yourself from source?

**Comment by gitnew2018** [comment]
It's in the [wiki ](https://github.com/gitnew2018/My-OpenPeriscope/wiki).
From NW.js you **need**  icudtl.dat, nw.pack and nw.exe.
From my repo you can **delete**: .idea, .gitignore, LICENSE, README.md
But, if you keep all the files, it will work just fine.

**Comment by Kamouser** [comment]
How can I use the **KEY** that generates the .txt report (broadcast log) of replay of private live stream ?
`**KEY:** d17GFie0qidaxmJJ/g/ryA==</br>`
