### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KaMyKaSii** [gitnew2018/My-OpenPeriscope#2]
I'm interested in using your repository as userscript since the Pmmlabs repository is not active. But I came to doubt, the links on Periscope_Web_Client.user.js should not refer to your repository instead of Pmmlabs?

**Comment by gitnew2018** [comment]
Its not ready for release and I never used it as userscript. 
I hope you realize that userscripts do not allow you to download videos, so there is no point to use my version anyway.
There are a lot of things that probably should be changed but as long as it works I'm not really concerned.
I will take a look at this later.

**Comment by KaMyKaSii** [comment]
@gitnew2018 I know that it is not possible to download through the userscript version. I have no problem with that, I use OpenPeriscope on Android (Yandex Browser + Tampermonkey) to capture the links and then use the M3U8 Loader to download. I tried installing your fork with the current commits but it did not work as userscript. Could you try to fix this (in your time)? Thank you!

**Comment by gitnew2018** [comment]
You can try now, I fixed it on Chromium 69, not sure if everything is going to work on Yandex.
And... I still don't know which new features you want from my version because it's main focus was on custom downloader ;P

**Comment by KaMyKaSii** [comment]
@gitnew2018 now it's working, thank you! I really liked the dark theme and also the differentiated background color for new broadcasts, so it's a lot easier to find a specific broadcast. Could you consider not clean the download link for replays after refreshing the page? Sometimes I need to refresh the page to get the M3U8 link from a new transmission but I eventually lose the replay links I had previously generated. And also a question, do you know of any way (other than your internal download manager) to download a live private stream using the M3U link generated by OpenPeriscope? Thank you one more time!

**Comment by gitnew2018** [comment]
I will see what I can do about links.
Both ffmpeg and my [node downloader ](https://github.com/gitnew2018/nodejs_peri_downloader)are able to do that but you have to provide cookies, link alone is not enough. I don't know any other program although i think there are others.

**Comment by gitnew2018** [comment]
Should work now as requested.

**Comment by KaMyKaSii** [comment]
@gitnew2018 Thank you! The links are still there after updating the page but for some reason the status "Download replay M3U" changes to "Live M3U link", it is not serious but would be nice if it could be fixed. I installed the terminal emulator Termux and then the nodejs and I was able to run your downloader. It works, but I had some problems. I tried to download the replay of a public broadcast and my Internet connection dropped in the middle of the download, so your downloader skipped some parts of the download, it is visible by the difference in size compared to the same download done without a connection drop. And when trying to download a private replay, an error occurred, even though the cookie is in the URL and the same link is playable in MX Player. When you have time, could you take a look at this? I have not yet had the opportunity to test the download of a private live broadcast, when I get the chance, I'll let you know
![screenshot_20180719-095606](https://user-images.githubusercontent.com/17092335/42954999-ca07a06a-8b53-11e8-937d-17fe31b5e066.png)
![screenshot_20180719-095615](https://user-images.githubusercontent.com/17092335/42955151-de04ca7a-8b53-11e8-8035-25d06cf4b705.png)
![screenshot_20180719-123238](https://user-images.githubusercontent.com/17092335/42955295-f2e58cf4-8b53-11e8-9202-b978a87f34b4.png)
![screenshot_20180719-125739](https://user-images.githubusercontent.com/17092335/42955583-34552604-8b54-11e8-965c-d78455df8a8e.png)

![screenshot_20180719-124025 01](https://user-images.githubusercontent.com/17092335/42955408-03a9d77a-8b54-11e8-94d0-284ef3c777cd.png)




. As always, thank you!

**Comment by gitnew2018** [comment]
Try new updates and if it doesn't help try single quotes ' ' around link.
You can also rename periscopeDownloader.js to for example x.js if you don't want to type this long name every time.

I didn't really expect it to work on a phone! :sunglasses:, unfortunately I can't get it to work on mine, so I can't test it myself :pensive:.

**Comment by KaMyKaSii** [comment]
@gitnew2018 The last update of MyOpenPeriscope has fixed the status of the link. I tested the new nodejs periscope downloader and it worked well for downloading the replay of a private transmission, I have not had a chance to try to download a private live stream. But I'm curious, how can I get the cookie considering that MyOpenPeriscope only provides the link (in the private replay the cookie is already present in the URL, would it be the same)? And may I know your device and setup? Maybe I can help make it work on your device. I'm running Android 6.0, I installed Termux, I opened it and waited for the initial configuration, then I ran "pkg install nodejs", after installed I ran "cd" to the nodejs periscope downloader directory and I could run the script normally. Just remember to enable the storage permission for Termux manually, for some reason it does not do this automatically and causes errors in the scripts that create files in the internal storage. And thank you for your dedication!

**Comment by gitnew2018** [comment]
@KaMyKaSii I added link to copy broadcast link, filename, and cookies for periscopeDownloader. There ~~is~~ was no way to get cookies in userscipt, only for private replays where it is encoded into redirection link.
In Termux i just cannot find folder with downloader.

**Comment by KaMyKaSii** [comment]
@gitnew2018 I'm very confused. At the present time, is it possible to get the cookie through usercript version or not? Because I generated the link from a private live and then copied through the "R_NodeDown" button and the content was with the token. Unfortunately when I opened Termux to test if it was possible to download, the stream was closed and deleted. And about Termux not working there, did you give the Storage permission manually? And sometimes Termux "ignores" the last character when pasting a command, so you should type the command manually, maybe that's it

**Comment by gitnew2018** [comment]
With the new link it is possible it wasn't before. R_ means it was already replay link anyway.

**Comment by KaMyKaSii** [comment]
@gitnew2018 in which case was the transmission already finished when I clicked to get the link? The strange thing is that the format of the link through R_NodeDown is different from what I am used to with the Copy link (from the private replay). Here is the content I had through R_NodeDown:

node periscopeDownloader.js "https://prod-video-us-east-1.periscope.tv/rI1FbDhLos4ZUCvIasssRt0aAoitw-oSE1Ichai7qAjM1XRcZ1-lUGhkaaVSfnKagDCjhhG_CtLpDBp8mdCUqg/live/us-east-1/dynamic_playlist.m3u8" "Censored name" "Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJBbGxvd2VkUHJvdG9jb2xzIjpbImhscyJdLCJCcm9hZGNhc3RJZCI6IjFNbnhuWnp5TkFNeE8iLCJHcmFudFR5cGUiOiJyZWFkIiwiR3JhbnRlZEF0IjoxNTMyMjg4NjcxLCJHcmFudGVkVG8iOiJwcml2YXRlIiwiU3RyZWFtTmFtZSI6InJJMUZiRGhMb3M0WlVDdklhc3NzUnQwYUFvaXR3LW9TRTFJY2hhaTdxQWpNMVhSY1oxLWxVR2hrYWFWU2ZuS2FnRENqaGhHX0N0THBEQnA4bWRDVXFnIiwiZXhwIjoxNTM0OTY3MDcxfQ.rmu-r726xh9QEoXPJ1-i1trumwLDHDSd3Rw31vSJhPM; Service=proxsee; Digest=kfueQsjTXbDkxobbIXXDRdYUbPCEQ7utaG3v4-otqBk; DirectToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJBbGxvd2VkUHJvdG9jb2xzIjpbImhscyJdLCJCcm9hZGNhc3RJZCI6IjFNbnhuWnp5TkFNeE8iLCJHcmFudFR5cGUiOiJyZWFkIiwiR3JhbnRlZEF0IjoxNTMyMjg4NjcxLCJHcmFudGVkVG8iOiJwcml2YXRlIiwiU3RyZWFtTmFtZSI6InJJMUZiRGhMb3M0WlVDdklhc3NzUnQwYUFvaXR3LW9TRTFJY2hhaTdxQWpNMVhSY1oxLWxVR2hrYWFWU2ZuS2FnRENqaGhHX0N0THBEQnA4bWRDVXFnIiwiZXhwIjoxNTM0OTY3MDcxfQ.rmu-r726xh9QEoXPJ1-i1trumwLDHDSd3Rw31vSJhPM; "

**Comment by gitnew2018** [comment]
Yes it was finished, unless it a bug :P because this whole link in your post is to live private broadcast.

Format is: node periscopeDownloader.js  "link" "name" "live private cookies".
Private replay link has cookie encoded in link but when you follow this link it will redirect you and give full cookies and different link. Internally the downloader works on received new link and those long cookies as in your post.

**Comment by KaMyKaSii** [comment]
@gitnew2018 but that's exactly it, I generated the link from a private live (at least I believe it was still in progress, since the color around it was red). Then the "R_NodeDown" appeared with the content I sent you. And all this through the usercript version. You said before that it was not possible to get cookies through the userscript version, could you explain the technical difficulty?

**Comment by gitnew2018** [comment]
Then it's probably my bug, 
In standalone version when you start downloading then in "Downloading" tab you could copy cookies from input field, in userscript version they just don't appear anywhere (only in console when developer mode is on, and as object which you would have to format properly to pass through command line...)

**Comment by KaMyKaSii** [comment]
@gitnew2018 being bug or not, it is definite, it is possible to download private lives using the usercript version to capture the link + cookie and Termux + nodejs to use the downloader
![screenshot_20180723-234717](https://user-images.githubusercontent.com/17092335/43114341-f86e212a-8ed4-11e8-9898-c5a57e85e2a0.png)

**Comment by gitnew2018** [comment]
Bug i was referring to was getting "R_NodeDown" when broadcast is live and copying live link from it.
I cannot replicate it so for now it stays unconfirmed.

**Comment by KaMyKaSii** [comment]
@gitnew2018 Can I make more requests for new features? A system to automatically try to get the replay link for lives still in progress, for example try to get the link every 5-10 seconds, and stop when successful. And also could do the same only to get the partial replay (https://api.periscope.tv/api/v2/accessVideoPublic?broadcast_id=LiveIDHere&replay_redirect=false&latest_replay_playlist=true)? And if possible with check box (to activate and deactivate, same as debug mode), so it will not be a problem for those who prefer My-OpenPeriscope in a more pure way. Thank you!

**Comment by gitnew2018** [comment]
Sure, requests are welcome.
For first request I actually did something like that for standalone version but because it saves to log file it won't work in userscript.
You want check box under debug mode to alter "copy url" to "copy partial replay url" correct?
I could just add another link :wink:

I also thought that it might be possible to download partial replay and live stream into one file with my nodejs downlader. It would require some work and I'm not sure if anyone even wants it.

**Comment by KaMyKaSii** [comment]
@gitnew2018 Can not you think of any approach for the system to get the replay link automatically working in userscript? I would like the "copy partial replay" URL button to be next to the "copy url". And I hope for example if I click on "Get stream link" and receive the result, and then the stream is deleted/banned, if I click again the "Get stream link" button the current status with the previous links will not disappear, so allowing me to still be able to copy at least the partial replay link (and maybe change the color from blue to red, thus indicating that the stream is no longer available). Do you think it would also be possible to create a "trash" area below, where would be lives that you generated the stream link but that were deleted (if it is possible to save this kind of thing in the cache)? About the checkbox, I mean having one for each feature I request and implemented, so users like me who like them and those who do not like will be pleased. And also I would like to ask, did you make any changes to the behavior of the "REFRESH" button? I have some friends using your fork and they said that compared to the original OpenPeriscope, often after the button is pressed the content is not updated, having to reopen the My-OpenPeriscope. Once again, thank you very much for your time and great work!

**Comment by gitnew2018** [comment]
@KaMyKaSii 
I'm still thinking how to approach auto replay links.
Partial replay links are almost there.
Trash area should be in following tab, bellow all broadcasts or rather make separate trash tab?
I didn't change how Refresh button works, only added new broadcast highlight and persistent links in the function and if anything in them fails it might prevent refresh from working. I cannot reproduce this bug, any error from console or browser where it happens to test would be helpful.

@Alvin388 
It's better to create separate issue for your questions and requests.
You are talking about my version? I never get corrupted videos.
Auto downloading replays kinda doesn't make sense because if broadcaster is quick to delete or banned it wouldn't download reliably anyway, in any other scenario you can download it manually.
Maybe i will add this.

In my version i don't use ffmpeg and thus cannot convert videos to mp4. In my opinion It's better to sort videos into 4 categories of rotation and mass convert them anyway.

**Comment by gitnew2018** [comment]
@KaMyKaSii 
Partial replay links added, probably not the way you imagined... and you have to turn them on in settings.

**Comment by KaMyKaSii** [comment]
@gitnew2018 I just updated userscript but I can not find where I can activate each type of link, I only see the checkbox for Debug mode. About the trash area, I think if possible a new tab will be better
![screenshot_20180808-104704](https://user-images.githubusercontent.com/17092335/43841156-ddc70eec-9af8-11e8-90e3-163f62b2355f.png)

**Comment by gitnew2018** [comment]
profile & settings (pencil near username) and Show partial replay(PR) links

**Comment by KaMyKaSii** [comment]
@gitnew2018 I had never thought to press that button, maybe you should change the icon to a gear or something. For me it looks good the way you did, but if I click again to generate the links from a deleted / banned transmission the previous links will disappear. Could you keep them and change the color to indicate that the transmission no longer exists? Thank you!

**Comment by gitnew2018** [comment]
In official periscope app and in open periscope there is pen icon, cba to change it :pensive:.
Keeping links, I will see what I can do.

**Comment by KaMyKaSii** [comment]
@gitnew2018 could you add two settings to enable / disable node periscope Downloader links, one for public broadcasts and one for private broadcasts? Because as I use other methods to record public broadcasts, I wish I could hide the NodeDown, but for private broadcasts it is indispensable. Thank you one more time!

**Comment by KaMyKaSii** [comment]
@gitnew2018 I am using the most current userscript and now the NodeDown button of private broadcasts does not generate the cookie

**Comment by gitnew2018** [comment]
@KaMyKaSii Added repeater that gets partial replay urls or replay url every x seconds. You need to turn notifications on in settings to activate refresh interval.
Also tell me how do you like the new following tab. I left the old one just in case people don't like it.

**Comment by KaMyKaSii** [comment]
@gitnew2018 First, I did like the new tab following. 

But I think she needs some modifications: 1. The system of capturing the link automatically works well! The only problem is that after finishing, the status of the button is "copy" rather than "Copy R_url" or "Copy PR_url" (if not successful with full replay capture), it would be good to change that.
2. It also has the problem where very long lives are far below, which ends up causing confusion. It would be nice to add a setting to keep lives always on top.

And about new features, I would ask for the following:
3. A button to copy username + user + broadcast description, this would help a lot who uses external means to do the downloads. 
4. Refresh the thumbnail automatically every 20 seconds for example, avoiding the need to press the REFRESH button (and lose links from some deleted / banned transmission). 
5. Similarly to the thumbnail, update the status color (red/blue) without having to press the REFRESH button.

And I'd also like to ask you to always increase the version number when doing some modification, so userscript managers (Tampermonkey in my case) will update automatically. 
As always, thank you very much for your willingness and great work!

**Comment by gitnew2018** [comment]
1. Ok.
2. Maybe I'll add setting for "classic" order. I like how sometimes new broadcasts appear on top of the list even when broadcaster deleted his replay, you still can download it if replay link was auto saved. With classic order it would get below live and replays then so it would be easier to miss it.
There is "Show interesting only" toggle so even when live broadcast is far away and you clicked "get stream link" or repeat checkbox then this toggle will show only those.

3. example: "OpenPeriscope @periscopeco live show for you.." as one string? and next to copy url?
4. and 5. You won't lose links after refresh.

I'm also thinking about adding checkbox above to hide all not live cards except highlighted new ones.

**Comment by gitnew2018** [comment]
@KaMyKaSii 
1. changed. 
2. Try with filters if it's any better.
3. Read above.
4. added. 
5. added as option (because of increased transfer).

**Comment by KaMyKaSii** [comment]
@gitnew2018 Thank you very much for considering everything I asked for. On the copy button, the way you suggested, maybe with a "-" to separate each type of information and "_" in place of blankspaces. Being positioned to the right of the "name (@username)". I'd also like you to put an option on filters to hide deleted streams, maybe also put a recycle bin icon on them. And I'm having some problems with the "repeat" function. Sometimes I click and after spending the time I have chosen (10 seconds), the "Copy PR_URL" button does not appear, but by checking my network traffic in the status bar every 10 seconds it is visible that MyPeriscope is doing the process, the only problem is that the link does not appear to be copied. If I click on the "Get stream link" button, both the "Copy URL" button and the "Copy PR_URL" button appear, but after 10 seconds MyPeriscope replaces them with nothing. I hope my description enlightens you to discover the root of the problem. Thank you one more time!

**Comment by gitnew2018** [comment]
I will add this later, now i want to eliminate bugs and prepare for release.
Unfortunately i cannot reproduce this bug so far. If you're using it on desktop when it happens then maybe check browser console if there is anything useful.

**Comment by ddpk** [comment]
I don't want to flood new requests so I'll ask here. What must you do to enable auto refreshing of partial replay links? "Added checkbox to activate auto getting partial replay links(drkchange22)" I don't see this yet. But that's ok. I have a suggestion for this! 

Maybe logs can include specific user only logs in the user's folder which adds partial replay links into it every X seconds for each broadcast (all broadcasts in same log file or preferably separated and the log filename = the broadcasst id) Maybe every time a LIVE starts recording, it updates this log with the latest partial link, then continues updating. So a newly followed user, appears on feed, starts recording, logs partial, keeps logging partial/recording live until broadcast finish. Logs don't need to be organized because of unique URLs. You can simply open the log and download each latest url. A further suggestion would be log only, since some don't record but only privates with open periscope. Thoughts? :) If a good suggestion I can open an issue for it for a later time. I know it might be too big an ask. Thanks

**Comment by ddpk** [comment]
I just checked the current logs, those are very well organized already actually, I really like it thanks! For me, I see it possibly missed logging a few users replays. I don't know what triggers it to re-log a new replay M3u8 link, but i'm guessing the user deleted it too fast in my case. Which is a nice thing about the possibility of my suggested partial logs. It's also very nice to have all these details, of broadcast start and title showing up the same for both -LIVE- and REPLAY. I haven't yet downloaded a replay so I understand those being logged are automatic as long as you check "Log" in settings? Does it only log if you refresh feed and/or click get stream link and the replay is available or does it get it quickly at broadcast end on its own?

**Comment by ddpk** [comment]
Speaking of logging automatically. The log file hasn't updated/modified for 2 days now it seems. I was only testing it so its not a problem but it only seemed to initially log all the broadcast replays on my feed that were already available. 

Also, something I might have done before made it so all of my feeds replays M3U8 were visible on their own as if I clicked "Get stream link" on all of them, but I didn't. This also hasn't happened to me for 2 days. Should both these things happen automatically or are they working as they should, being a one time thing?

**Comment by gitnew2018** [comment]
@ddpk It's better to create new issue for your questions/requests.

I think I need to explain how it works a little.

Each time you click refresh(on following tab) a request is sent to periscope to send back a list of broadcasts that should appear on your following broadcasts feed.
you can see how it looks here: http://static.pmmlabs.ru/OpenPeriscope/ under /followingBroadcastFeed 
If you check "Enable notifications" or "Enable automatic downloading of the following items" then program sends the same request every "Notifications refresh interval" seconds.

One problem is when you flood their servers with too many requests (for example interval < than 3s) they will block you for some time.

Second thing is response does not include video link so you need to send different request each time you want to get video link.
So if you select too many broadcasts to get partial links every interval you might get over their limit and get blocked. 

Right now Replay links are requested automatically when state of broadcast has changed between old and new response.

**Comment by ddpk** [comment]
Okay, thanks. Makes sense. I understand it is an unrealistic request. I'll be more careful with the intervals on repeating partial links.
