### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by stark-02** [gitnew2018/My-OpenPeriscope#20]
https://github.com/gitnew2018/My-OpenPeriscope/blob/84e184521169af0ed867973c28853f61ff5d0447/Periscope_Web_Client.user.js#L2329

This line was throwing an error because of the spelling

**Comment by gitnew2018** [comment]
This spelling error is in the comment so it cannot throw errors, it has to be something else around there.
I'm not able to reproduce, can you tell me when it happens, what do i have to do to make it happen.

**Comment by Kamouser** [comment]
the erros is in all versions, even in the white classic, it only works on the google chrome script
![error1](https://user-images.githubusercontent.com/50481149/62165854-be3e5b00-b2f5-11e9-854d-c202ee5d4cc7.JPG)
