### ISSUE TITLE
sign in not working

### ISSUE THREAD

**Issue by oneohsixx** [gitnew2018/My-OpenPeriscope#21]
I was using this version a little while ago, then lastnight went to link a new account via twitters login , but the page just loads blank.. and nothing happens..  the other open periscope has the same issue.. the two instances i already have running are still working fine, but new accounts cannot be linked... could someone advise on what the issue is please.

**Comment by gitnew2018** [comment]
Check the console for errors.

**Comment by oneohsixx** [comment]
thanks for the quick reply...  this is the only message i see when i click console 
Uncaught ReferenceError: require is not defined

**Comment by Kamouser** [comment]
the erros is in all versions, even in the white classic, it only works on the google chrome script
![error1](https://user-images.githubusercontent.com/50481149/62166130-5a686200-b2f6-11e9-9a13-07ceac7f1229.JPG)

**Comment by oneohsixx** [comment]
glad its not just me... hope its a simple fix 😢

**Comment by Kamouser** [comment]
@oneohsixx in the version script it only has simple functions, is incomplete

**Comment by oneohsixx** [comment]
@Kamouser i just noticed haha. atleast we know it works there so its not blocked by twitter or peri.  im sure will be good news in a day or so.

**Comment by gitnew2018** [comment]
Just to let you know, in bare nwjs without any modification twitter.com is also blank.
It might not be easy to fix.
As a workaround, you can sign in in script version, copy session id and then login in app with it.

**Comment by oneohsixx** [comment]
thanks for the reply.. ive logged in with the script but cant find out how to find the session id, ive looked with dev tools in chrome but cant find what i need.. if you get time please could you explain exactly how to do this.

**Comment by gitnew2018** [comment]
In console open `ready!  Object` , the cookie is session id. Use it without quote marks.

**Comment by Kamouser** [comment]
> 
> 
> In console open `ready! Object` , the cookie is session id. Use it without quote marks.

by the avatar that got @gitnew2018 gitnew we realize that we bring it crazy of so many issues LOOOL.
At the moment you can only log in with the SID

**Comment by oneohsixx** [comment]
thanks for trying to help. i found the cookie id but have no  clue what im supposed  to be adding it to or pasting it, and i expect you are very busy so i guess im going to have to just wait and see if anything changes in the future.. thanks for all the hard work and effort up to now.. we all appreciate it

**Comment by oneohsixx** [comment]
actually, ive now got it working using the sid login, by logging in with my regualar browser and using the extension cookies.txt to find the sid and literally just pasting it in... works out even better because i dont have to keep making twitter accounts :D

**Comment by gitnew2018** [comment]
I have added compatibility* with newest nwjs, It's in the nwjs_0.40 branch.
Sign in with twitter works there.

*some things (like watching broadcasts) don't work yet.

**Comment by alfabetico** [comment]
> actually, ive now got it working using the sid login, by logging in with my regualar browser and using the extension cookies.txt to find the sid and literally just pasting it in... works out even better because i dont have to keep making twitter accounts :D

SID corresponds to _twitter_sess in cookies.txt?
I try it and not work

**Comment by Mironyan55555** [comment]
> actually, ive now got it working using the sid login, by logging in with my regualar browser and using the extension cookies.txt to find the sid and literally just pasting it in... works out even better because i dont have to keep making twitter accounts :D

Hello ))) Please tell me in more detail how to go through SID and what Assembly you used.

**Comment by bootyislife** [comment]
> 
> 
> I have added compatibility* with newest nwjs, It's in the nwjs_0.40 branch.
> Sign in with twitter works there.
> 
> *some things (like watching broadcasts) don't work yet.

Where do we post the session id? I'm just sitting here with this id that I've tried pasting literally everywhere in the app and it doesn't do a single thing. Also, logged in on the account on 2 different browsers. Would really wish to not go through an annoying process..

**Comment by gitnew2018** [comment]
@bootyislife You put it in the only input field there is...
Maybe read [this](https://github.com/gitnew2018/My-OpenPeriscope/issues/35#issuecomment-522565642)
It's actually easier and faster than standard login when you know how to.

**Comment by bootyislife** [comment]
> 
> 
> @bootyislife You put it in the only input field there is...
> Maybe read [this](https://github.com/gitnew2018/My-OpenPeriscope/issues/35#issuecomment-522565642)
> It's actually easier and faster than standard login when you know how to.

Yeah I didn't realize it needed to be pasted into the consumer key spot.. Thought it needed to be somewhere in the program console. I'm dumb, my bad. Thanks man ;p

**Comment by gitnew2018** [comment]
It works with new nwjs closing.
