### ISSUE TITLE
Auto donwloads are not working

### ISSUE THREAD

**Issue by owl46** [gitnew2018/My-OpenPeriscope#22]
I have the "Enable automatic downloading" box checked with all the options, but either public or private broadcasts are working or showing in the download manager tab, unless i manually add them through the "Get stream link" option, which works fine.

Broadcasts supposed to be autodownloaded are shown correctly in the log txt file though, but video files or user folders are not created.

I have all the files are up to date, using the built standalone version.
Thank you for your work and your help.

**Comment by gitnew2018** [comment]
It doesn't seem to work if you login with SID. I need to check why.

**Comment by gitnew2018** [comment]
You need to uncheck "Enable automatic downloading" and check it again.

**Comment by Kamouser** [comment]
it's normal the 6 seconds delay in automatic downloads ?

**Comment by owl46** [comment]
> You need to uncheck "Enable automatic downloading" and check it again.

Problem solved. Thanks a lot!

**Comment by gitnew2018** [comment]
@Kamouser  what do you mean?

**Comment by Kamouser** [comment]
@gitnew2018  6 seconds delay always occurs in automatic downloads (6 seconds of transmission that are lost from when the transmitter starts direct)  sometimes ocurrs In both versions (my-open and openperis).
this will not depend on the processor you have installed on your pc ? time delay when you start recording?
or is it a conection topic of the user transmitting ?
PD: this happens sometimes

**Comment by gitnew2018** [comment]
@Kamouser when `Notifications refresh interval` is set to 15 then it probably will miss first few seconds. Experiment with it set between 5 and 10.

**Comment by Kamouser** [comment]
![example](https://user-images.githubusercontent.com/50481149/62352182-ed172580-b4dd-11e9-9139-76249e9043e6.png)
this is due to the reporting interval ?

**Comment by gitnew2018** [comment]
@Kamouser did it solve your issue?
