### ISSUE TITLE
Cap after being added to a group

### ISSUE THREAD

**Issue by Alvin388** [gitnew2018/My-OpenPeriscope#3]
Hi!
One problem I came across is OP not starting to cap when you are added to the group **after** the broadcast had already started.
Would it be possible for OP to check if broadcasts are going on in the background and if not picked up already - start downloading the cap at 00m01s?
like putting `?t=00m01s` at the end of the broadcast URL.
Thanks in advance! 😃

**Comment by gitnew2018** [comment]
It doesn't automatically start recording when broadcast doesn't show up in the following feed. When you use first release of My-op you can't download "`?t=00m01s`", but when you use current files from repository, you can download partial replay and record live broadcast at the same time. Unfortunately it will create 2 video files. I think it is possible to make only one file but it would require to modify downloader.
You could also keep clicking on get stream link until broadcast ends then get whole replay link, or partial that is almost complete.

**Comment by Alvin388** [comment]
I see.. no need to make it unnecessarily complicated I think! 😉 
What do you think about an extra option for the partial replay:

Option 1: starts at the beginning of the broadcast - ends at that specific moment the broadcast was when you clicked "download".
Option 2: starts at the beginnig of the broadcast and records that broadcast until it finishes. 

Would option 2 be possible/practical?

**Comment by gitnew2018** [comment]
Option 1, this is how partial replays work.
Option 2 as said above, I think it can be done but I would have to modify downloader.

**Comment by DonPepeSun** [comment]
I dont know if my opinion could serves , but you could see the app "Snagscope" for android,this app try to download all the transmition since the beginning. You could see the code of the app and get an idea.

For now, i download the lives and parcial parts, and using ffmpeg ,join both videos.
