### ISSUE TITLE
Can you add a filter to the "Top" tab like in "Following2"?

### ISSUE THREAD

**Issue by Qulaish** [gitnew2018/My-OpenPeriscope#31]

**Comment by gitnew2018** [comment]
I can, although i personally prefer to use sites like http://en.peritter.com/ or http://liveomg.com/ for finding interesting broadcasts.

**Comment by Qulaish** [comment]
it would be convenient if you could filter the broadcasts by language and hide the "producer"

**Comment by gitnew2018** [comment]
Now language and producer filters from following section are global.

**Comment by Uek32** [comment]
disable filtering on user tab
