### ISSUE TITLE
Some live streams are not automatically downloaded

### ISSUE THREAD

**Issue by Kamouser** [gitnew2018/My-OpenPeriscope#35]
I've been testing these last few days and 1.5% fail to download just creates the empty folder
I think it would be a connection failure at the time of capture, or the user will have bad connection, but sometimes I check the replay (which could not be recorded) in the user's profile and this normal and I can download it but manually...
in each repetition it also identifies with sky-blue and dark blue
my connection is very good.

you'll have a function to insist on re-downloading automatic the failed live stream ?

**Comment by Halinks** [comment]
I got the same problem. There are also difficulties when the broadcaster drops the cam, they get messages (vibration + pop ups), or their wifi connection is lagging for a bit. 
My-OP caps up to the point of lag, then stops capturing, no matter how long the live continues.
Had that happen awfully often lately... :(

**Comment by gitnew2018** [comment]
These are two separate bugs. Nonetheless thank you for reporting them. 
Nowadays, I don't really use the app myself(except testing), so I'm unable to catch some of the bugs.

**Comment by Halinks** [comment]
Any progress on this @gitnew2018 ? It makes OP really unreliable :(

**Comment by gitnew2018** [comment]
To be honest, I only got on with it yesterday and I cannot reproduce so far.
I got fix for the first bug and a few other rare bugs ready.

**Comment by gitnew2018** [comment]
I was able to reproduce it. Unfortunately it's a tough one as the methods for debugging I usually use don't give me enough information.

**Comment by Kamouser** [comment]
#2b194b4

**Comment by Kamouser** [comment]
#2b194bf6a4039d6d530f55927ecfe6536d892dd6

**Comment by Kamouser** [comment]
I'm currently using an older version that doesn't present this error:
https://github.com/gitnew2018/My-OpenPeriscope/tree/2b194bf6a4039d6d530f55927ecfe6536d892dd6
in that version temporary folders are created with the parts (chunks) it downloads all
it works perfectly if you want to download the PR LINK manually, doesn't present the error
#18
if you could re-add that download method with the ultiams versions...

**Comment by gitnew2018** [comment]
Try now, @Kamouser and @Halinks

**Comment by Mironyan55555** [comment]
Hey. Can you tell me how to set up automatic downloading of broadcasts? Which path to save and how to do it. May have missed something? )))

**Comment by gitnew2018** [comment]
Go to settings (pencil under your avatar).
Check `Enable automatic downloading of the following items` and category of broadcasts you want to download.
`Following broadcasts` is not working properly, it is better to use `Selected users broadcasts`.
By default, they are downloaded to the folder where the program is, you can change it In settings under `Downloads path:`.

**Comment by Mironyan55555** [comment]
Thanks for the explanation. 
But I can not log in My-OpenPeriscope v0.1 ((( people write that you need authorization via SID, but how to do it? 
I understand correctly that userscript version does not automatically download, only v0.1. 
Please tell me )))

**Comment by Halinks** [comment]
Awesome! I'm gonna go live and try to break it by lagging. Will post my results when I'm done.

**Comment by gitnew2018** [comment]
@Mironyan55555 Don't use release version it's very old. You need to read wiki how to build it by yourself. It's pretty easy.
If you already have userscript version running, open browser console, open `ready!  Object` and the cookie = SID.

**Comment by Mironyan55555** [comment]
I have tried many ((( But apparently don't understand something. 
SID from cookies took out, but how to enter through it???

For me really it's all a mystery ) Tried to collect but got only a window NW.JS........what's next, I do not understand((( If possible, please advise.

**Comment by gitnew2018** [comment]
download All files from this repository and unpack them into NWJS folder
and it should work(except chat)
Screen from wiki:
![screenshot](https://user-images.githubusercontent.com/37026885/44465622-63e54680-a61e-11e8-86b9-44ea0b576452.jpg)

**Comment by Kamouser** [comment]
**the download  stopped and generated a error text file**
![nuevobugg](https://user-images.githubusercontent.com/50481149/63206358-2bd5df80-c089-11e9-96b1-711b233b536b.png)

**Comment by Kamouser** [comment]
only happened to me once by downloading manually
![nuevobugg](https://user-images.githubusercontent.com/50481149/63213731-44281780-c0e6-11e9-9d30-8394a6ab0dad.png)
the download stopped and Generated a .txt file with the error

**Comment by gitnew2018** [comment]
This error happens when disk is busy. I have never seen this happen on my system even when downloading 20 broadcasts at the same time, you probably don't have ssd. I might look into ways to save broadcast chunks more efficiently.

**Comment by Kamouser** [comment]
I'm going to have to free up space.
will continue testing

**Comment by Mironyan55555** [comment]
Hey. Many thanks for the answer!!!
All done as written in the wiki (except nodejs.org). On something does not come ((( 
I Enter SID, I press "Sign in with SID" and what does not occur. I insert the key, but the window continues to hang. 
I can not correctly specify the SID? (taken from cookies, it is a 9 digit code. Right?)

**Comment by gitnew2018** [comment]
@Mironyan55555 SID is 177 chars long.

**Comment by Mironyan55555** [comment]
Hey. Probably not given to me((( the Second week trying to figure it out, but I can't do anything. Not start. 
That just did not enter in "Sign in with SID": personalization_id, guest_id, twid, _twitter_sess... Or where I can find SID. 
Opened the console, Opera - Application - cookies. And not find session. 
It seems so simple..... And it turned out as the Bermuda triangle )))

**Comment by gitnew2018** [comment]
In Opera - Application - cookies you should have:
```amplitude_id
bitmovin_analytics_uuid
loginissignup
oauthorigin	
pscp-csrf
rst	
sid
stateToken
```
guess which one you need...

**Comment by Kamouser** [comment]
**Bug confirmed: My-OpenPeriscope does not record automatic those live streams of users who have bad internet connection**

**Comment by gitnew2018** [comment]
@Kamouser Can you try downloading with the new version of nwjs. I couldn't make it crash even once, downloading around 40gb for a whole day. I think that the old nodejs was bugged.

**Comment by Kamouser** [comment]
@gitnew2018  i haven't continued to try this error for a while now.
I know that in this version: https://github.com/gitnew2018/My-OpenPeriscope/tree/2b194bf6a4039d6d530f55927ecfe6536d892dd6 (uses the NWJS V0.12)
in that version this problem doesn't exist, didn't miss a single discharge.

but I'll start to experience the behavior of downloads in the new version of MyOpen and NWJS.

**Comment by gitnew2018** [comment]
I believe it is fixed.
