### ISSUE TITLE
Feature Request: User Management

### ISSUE THREAD

**Issue by Max104t** [gitnew2018/My-OpenPeriscope#36]
I like to mimic the product feature to list all my following / followers in one view..
Thanks

**Comment by gitnew2018** [comment]
User section? ...

**Comment by Max104t** [comment]
Are you suggesting upgrading the user section?

In user section only one user can be viewed.. I like to see all `following` so I can toggle `selected` on them in one place.. https://www.periscope.tv already gives me a list of all following, and followers which I can manage..

**Comment by gitnew2018** [comment]
I meant that you can display all following and followers in this section already.
