### ISSUE TITLE
not urgent: small fix: Change to main repository..

### ISSUE THREAD

**Issue by Max104t** [gitnew2018/My-OpenPeriscope#47]
https://github.com/gitnew2018/My-OpenPeriscope/blob/c0fdefd4f85c030ac53614eb660af6f56ee55ed6/Periscope_Web_Client.user.js#L22

This impacts only user script..

Please change to main repository.. I've already merged upstream/master -> orgin/support-groups so it should be fine for now

**Comment by gitnew2018** [comment]
Thanks.
