### ISSUE TITLE
Request: Add language in broadcasts_log.txt

### ISSUE THREAD

**Issue by Kamouser** [gitnew2018/My-OpenPeriscope#49]
it would be possible to add an option to know the language ?
`new_list[i].stream_language` ???

**Comment by gitnew2018** [comment]
Sure.

**Comment by gitnew2018** [comment]
Turn on `debug mode` open console and check what are the properties. (btw you're close).

**Comment by Kamouser** [comment]
I've seen the client.js web as clearly as I've got `new_list[i].stream_language` , but it shows me ''undefined'' I have no idea what would be missing...
