### ISSUE TITLE
File name suggestion

### ISSUE THREAD

**Issue by Putsomethininthemicrowave** [gitnew2018/My-OpenPeriscope#5]
Is it possible to make OP put something like:
=PB= for Public
=PV= for Private
=PR= for Partial Replays
for the specific capture in the file name? 
This would avoid lots of confusion when you are capturing all of those for a single broadcaster!

**Comment by gitnew2018** [comment]
Good idea, I will see what can be done about it.

**Comment by gitnew2018** [comment]
added.
