### ISSUE TITLE
Buffer?

### ISSUE THREAD

**Issue by bootyislife** [gitnew2018/My-OpenPeriscope#53]
(node:17204) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by gitnew2018** [comment]
There are some deprecated methods used, because NWJS v0.12.3 is so old that it doesn't support the new and fixed ones.
