### ISSUE TITLE
Migrating to new NW.js 

### ISSUE THREAD

**Issue by gitnew2018** [gitnew2018/My-OpenPeriscope#55]
v0.2.07 Released

**Comment by Kamouser** [comment]
I'll try it later
I'll buy you a beer

**Comment by gitnew2018** [comment]
@Kamouser Thanks but I do not accept any donations. Its my hobby.

**Comment by pistolero330** [comment]
can you help me ? i cant log in twitter api wont work. everything is updated still cant login. please help man.

**Comment by gitnew2018** [comment]
@pistolero330 what is the issue? where are you stuck at?  I just tried and it works for me.

**Comment by pistolero330** [comment]
@gitnew2018 

1- https://imgur.com/a/6YiKNMn 

2- https://imgur.com/a/xHW4msd

3- https://imgur.com/a/gsGOTu9

can you help me ? thanks man

**Comment by gitnew2018** [comment]
You got old NWJS, check my updated [wiki](https://github.com/gitnew2018/My-OpenPeriscope/wiki), I use v0.40.2 SDK.

**Comment by pistolero330** [comment]
@gitnew2018 

thank you so much its working now. gracias

**Comment by Kamouser** [comment]
Hi, I've been running some tests with the new version of nwjs(v0.40), in conclusión:
* ceases to be compatible with Windows 7. works with https://dl.nwjs.io/v0.30.0/
* Unnecessary files in common (delete): swiftshader
                                                             credits.html
                                                             d3dcompiler_47.dll
                                                             libEGL.dll
                                                             libGLESv2.dll
                                                             nw_200_percent.pak

**Comment by gitnew2018** [comment]
Weird I tried v0.41.2 in Virtualbox win7 and it works. I need to verify if those files are safe to delete annd maybe find others and release on one of the new nwjs.

**Comment by Kamouser** [comment]
the new versions of nwjs, do not have the address bar and the console ?

**Comment by gitnew2018** [comment]
It doesn't have address bar, nwjs sdk version has console F12 or right click inspect.

**Comment by Kamouser** [comment]
nwjs sdk version, have a direction bar ?

**Comment by gitnew2018** [comment]
It does not. Workaround is:  type `location.href` in the console to get the address and `location.href = "your new address"` to set it.

**Comment by Kamouser** [comment]
Hi, in the new version of NWJS you can open multiples open.exe ? I can only run one.

**Comment by gitnew2018** [comment]
You cannot as easily as it used to be, maybe there is some chrome flag you can add to change it. Right now you can just copy whole folder to open another window.
