### ISSUE TITLE
what is consumer secret?

### ISSUE THREAD

**Issue by utanmaz** [gitnew2018/My-OpenPeriscope#56]
help me pls.. i have not this code and i I can't find.

**Comment by gitnew2018** [comment]
Search on google for Periscope Secret Key pastebin

**Comment by utanmaz** [comment]
> Search on google for Periscope Secret Key pastebin

thanks!   but how do i download video? I didn't see anything about downloading.

**Comment by gitnew2018** [comment]
If you managed to sign in, spend some time exploring the app.

**Comment by utanmaz** [comment]
I couldn't find it. would you please tell me?

**Comment by gitnew2018** [comment]
![Clipboard04](https://user-images.githubusercontent.com/37026885/65013797-d1949c80-d91c-11e9-9812-f48d5591a01c.jpg)

When you click `get stream link` you should see `record` and `download pr` (you need to enable `Show partial replay(PR) links` in settings for that)
There is `download` link to combine them both into one and download whole broadcast.

You can also go to settings (pencil under your avatar), check `Enable automatic downloading of the following items` + kind of broadcasts you want.

**Comment by utanmaz** [comment]
I'm sorry, but I think there's something wrong with me.
the app looks like this
![asd](https://user-images.githubusercontent.com/35738012/65035173-38cc4400-d951-11e9-8cc2-2727da8a31c4.JPG)

![ss](https://user-images.githubusercontent.com/35738012/65035174-38cc4400-d951-11e9-8ecc-95c69db126f7.JPG)

**Comment by gitnew2018** [comment]
I think you are using https://github.com/Pmmlabs/OpenPeriscope as a userscript.
read wiki how to build my version https://github.com/gitnew2018/My-OpenPeriscope/wiki - or downoad https://github.com/gitnew2018/My-OpenPeriscope/releases

**Comment by utanmaz** [comment]
I downloaded it from the link. but after entering the code, the White page opens.

dev loops:
Uncaught ReferenceError: require is not defined.

**Comment by gitnew2018** [comment]
https://github.com/gitnew2018/My-OpenPeriscope/issues/21
The release version is based on old NWJS v0.12.3, where this problem occurs, it's the same with original open periscope standalone. you can login with Session id only.

That's why its better to build it yourself.

**Comment by utanmaz** [comment]
thanks!  built it myself. but I still can't download. 


#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 0000008A8A1FE610

**Comment by gitnew2018** [comment]
Does nwjs start by itself ?
What did you do?
I just tried with 0.41.1 and no problem here.

**Comment by utanmaz** [comment]
I tried it again with normal nwjs version and it worked now. thx!
