### ISSUE TITLE
Updated all the code and now doesnt look right

### ISSUE THREAD

**Issue by oneohsixxx** [gitnew2018/My-OpenPeriscope#57]
Hi been using this for months and today decided to update with the latest updates from the past two months to get the group settings... now when i open the application up it looks wrong,. the background is all white, and everything is pushed over to the left... and anything i click opens up on the left under the menu instead on on the right like it use to..... ive included some screen shots.... im not sure if this is how it is is suppose to look now??? if not could anyone advice on getting the old look back?? i log in using the ssid if this helps.
![SCREEN 11](https://user-images.githubusercontent.com/55542508/65247264-0143d000-dae8-11e9-99bd-2568a2cc547a.png)
![SCREEN 1](https://user-images.githubusercontent.com/55542508/65247265-0143d000-dae8-11e9-9916-b0a02e70e394.jpg)

**Comment by gitnew2018** [comment]
The code in repo no longer compatible with  NWJS v0.12.3, you can download latest release or read updated wiki on how to build it with newest nwjs.

**Comment by oneohsixxx** [comment]
After it didnt work right the first time i read the install  instructions to see if anything changed, and installed the latest version 0.41.1 with sdk and it was still the same ... i will do a seperate total rebuild from scratch and see if the issues fixed.

**Comment by oneohsixxx** [comment]
ahh i must have missed something out the first time when copying files... a new rebuild have solved the issue and it looks how it should..  thanks for all your time and effort.
