### ISSUE TITLE
i cant login with twitter

### ISSUE THREAD

**Issue by ninosel** [gitnew2018/My-OpenPeriscope#58]
[image](https://i.imgur.com/PuB48Vs.png) can you help? Thanks

**Comment by gitnew2018** [comment]
https://github.com/gitnew2018/My-OpenPeriscope/issues/21
You can only sign in with session id when you use old version.
You can build new version where it works:
https://github.com/gitnew2018/My-OpenPeriscope/wiki

**Comment by ninosel** [comment]
i tried  My-OpenPeriscope v1.4  still not working i never installed nwjs so i dont know where is nwjs folder program was working yesterday Thanks.

**Comment by ninosel** [comment]
> #21
> You can only sign in with session id when you use old version.
> You can build new version where it works:
> https://github.com/gitnew2018/My-OpenPeriscope/wiki

i tried My-OpenPeriscope v1.4 still not working i never installed nwjs so i dont know where is nwjs folder program was working yesterday Thanks.

**Comment by gitnew2018** [comment]
This app is based on nwjs. 0.1.14 is on NWJS v0.12.3 where twitter doesn't work.
You don't need to install it just download unpack and paste files from my repository.

**Comment by ninosel** [comment]
> This app is based on NWJS, release version is on nwjs v0.12.3 where twitter doesn't work.
> You don't need to install it just download unpack and paste files from my repository.

i downloaded nwjs sdk v0.41.2.rar file unpack to my-openscope folder still not working :(

**Comment by gitnew2018** [comment]
Read the wiki. And look at the screenshots there.

**Comment by ninosel** [comment]
> Read the wiki. And look at the screenshots there.

okey i solved thanks
