### ISSUE TITLE
nwjs RAM problem

### ISSUE THREAD

**Issue by ninosel** [gitnew2018/My-OpenPeriscope#60]
i click to 1 times nwjs.exe after opens 5-10 nwjs.exe in the task manager.I noticed when my computer started to freeze. Can you help me? Thanks
 [IMAGE](https://i.imgur.com/LfiCdCR.png)

**Comment by Kamouser** [comment]
try to delete and create another directory, the new nwjs takes a few seconds to start, it's patient only double click.

**Comment by gitnew2018** [comment]
It starts with 4 processes when you download broadcast then it spawns new process for each and there is that loading circle cursor for a second or so, that's normal. What kind of freezing do you get?

**Comment by ninosel** [comment]
njws.exe's each one for minimum uses 20MB, downloaded file doesnt close in download manager last when I look computer was using 2 gb ram.There was no such problem when I used relase My-OpenPeriscope v0.1. Sorry for english Thanks.

**Comment by gitnew2018** [comment]
As far as i remember It always had some memory leaks. For me it hardly ever exceeds 1gb, usually stays around 300mb.
Refresh download manager, also check task manager if download processes are still running.

**Comment by owl46** [comment]
I've had more problems with the CPU usage recently. I've noticed that after a few hours with the program running, at some point the CPU usage raises a lot, sometimes up to a 50% or more in my computer. I don't know what triggers it (it's not the number of simultaneous downloads).

It's not a big deal, i usually restart the program a couple of times if i let it running all day. But it would be nice to know some way to control it. It's not very nice to see the computer running almost at a 100% of CPU.

**Comment by gitnew2018** [comment]
@owl46 I don't really pay attention to cpu usage ever since i bought 12 threaded one, I'm going to take a look if there is anything going on.

**Comment by ninosel** [comment]
downloaded file doesnt close in the download manager [image](https://i.imgur.com/8Gs6hXv.png)
also does not close in the task manager [image](https://i.imgur.com/R4RrZfI.png)

**Comment by gitnew2018** [comment]
I don't know what is going on. You could try different version of nwjs.

**Comment by wj78** [comment]
Hello,

I am new here. First of all, @gitnew2018 I really want to thank you for the wonderful job you are doing with My-OpenPeriscope !

I performed some investigations on the RAM and CPU issue. I think that the origin is the automatic download of replays with the command line starting with "nw.exe downloaderNode.js -url undefined -rurl https://...".

As we can see in the screenshot, these processes take a huge amount of RAM and CPU, growing continuously, and never automatically stop :

![Annotation 2019-10-01 210812](https://user-images.githubusercontent.com/56003699/65993791-3100b980-e492-11e9-9094-8a916b003a98.png)

This issue does not exist with the command line ""nw.exe downloaderNode.js -url https://...".

I hope it will help to solve the issue. Tell me if you need more support from me

**Comment by gitnew2018** [comment]
@wj78 thanks, that's really helpful.

**Comment by Kamouser** [comment]
This would be the problem? DownloaderNode.js
![aqui](https://user-images.githubusercontent.com/50481149/66083140-16861900-e542-11e9-8542-09be952db595.JPG)

**Comment by gitnew2018** [comment]
No, I have it fixed, will commit later with some other changes.

**Comment by owl46** [comment]
@gitnew2018 Thanks, last update looks good after testing it for a few hours. CPU usage looks stable in low values for me now.
