### ISSUE TITLE
OpenPeriscope isn't auto downloading

### ISSUE THREAD

**Issue by ghost** [gitnew2018/My-OpenPeriscope#65]
Yes I've enabled it in the settings specifically for followed and for selected users. I've tested with over 10 or so just now and none of them have auto downloaded. First when you select or follow it should start the download of their current live, but even after hitting download on their live the next ones won't be recorded.

Edit: Also, would it be possible for an option to download privates only from selected users as well? Or, does the selected user function also download privates from said user?

**Comment by gitnew2018** [comment]
Heh, You're right It doesn't seem to work. Strange that you are the first one reporting that.
Selected should download all broadcasts public and private.

**Comment by ghost** [comment]
> 
> 
> Heh, You're right It doesn't seem to work. Strange that you are the first one reporting that.
> Selected should download all broadcasts public and private.

Yeah surprised I didn't see it here so thought I'd post. If you have just privates checked then it always works, at least majority of the time.
