### ISSUE TITLE
(feature request) FFMPEG download buttons

### ISSUE THREAD

**Issue by KaMyKaSii** [gitnew2018/My-OpenPeriscope#67]
Just like in the old versions of kewalsk fork, could you add buttons that automatically copy to clipboard the ffmpeg command to download a particular stream?
https://github.com/kewalsk/My-OpenPeriscope/commit/8811cdd37dffdd1c2502edbd517e6639e1ce66c3

And about deleted/banned private transmissions, the already genetared m3u8 links remains accessible but apparently the Periscope server is blocking access to the decryption key, so you don't have a playable media file. Do you think it is possible to make My-OpenPeriscope access the key in advance, convert it to hexadecimal and use it with the "cryptokey" parameter in ffmpeg (and also on your Node Peri Downloader copy button)? From what I saw in the documentation this is the ffmpeg parameter to use a custom key but I'm not sure. I ask this because I have a bad internet connection and I can't always download the broadcast at that time, so it would be nice to have the command saved to the clipboard with all the necessary information (m3u8 url, cookies, decryption key) to download  a private broadcast even after being deleted/banned.
Thank you!

**Comment by gitnew2018** [comment]
Why do you prefer ffmpeg? Decryption keys are already saved and work in standalone, just not in userscript. Also standalone has log broadcasts(with link and key) to a file option.

**Comment by KaMyKaSii** [comment]
> Why do you prefer ffmpeg? Decryption keys are already saved and work in standalone, just not in userscript. Also standalone has log broadcasts(with link and key) to a file option.

I can't use the standalone version, just the userscript version because I use My-OpenPeriscope on my Android device through Kiwi Browser with Tampermonkey, and to download I use Termux terminal emulator (with ffmpeg and nodejs installed). I would like a ffmpeg copy button as an alternative because in Termux running ffmpeg is almost instant while Node Peris Downloader takes almost six seconds to start the download. If you are not willing to do this, could you at least adapt My-OpenPeriscope (userscript) to copy and Node Peris Downloader to receive the decryption key as a parameter?

**Comment by gitnew2018** [comment]
I kinda neglected nodejs_peri_downloader, It should be able to combine replay and live into one just like it does in my-op. Unfortunately I don't have much energy nowadays so it might take a while.

**Comment by KaMyKaSii** [comment]
> I kinda neglected nodejs_peri_downloader, It should be able to combine replay and live into one just like it does in my-op. Unfortunately I don't have much energy nowadays so it might take a while.

With all due respect, I didn't quite understand why you talked about nodejs_peri_downloader being able to combine replay (partial replay?) + live as the focus of this issue is to save the decryption key in userscript version via the PR_NodeDown / R_NodeDown button of private broadcasts. But if you are willing to do this, you can take as long as you need without any hurry. Thank you!

**Comment by gitnew2018** [comment]
Because I thought that the reason you prefer ffmpeg is that slow start makes you miss couple seconds of broadcast. 
Sure, updating downloader + being able to copy link and key should take around 20h of work.

**Comment by KaMyKaSii** [comment]
> Because I thought that the reason you prefer ffmpeg is that slow start makes you miss couple seconds of broadcast.
> Sure, updating downloader + being able to copy link and key should take around 20h of work.

Yes, it sure is bad to miss those 6 seconds of streaming before the download starts, but it is negligible, at least for public broadcasts, because there is also the partial replay button. But this gets worse on private broadcasts because in this time of 6 seconds the broadcast can be deleted or banned and as the userscript version does not save the decryption key, downloading becomes impossible.
And I'm so sorry that these modifications are so laborious. I really appreciate your work and more for doing it even though you get nothing for it.  Thank you one more time!
