### ISSUE TITLE
Can't view chat

### ISSUE THREAD

**Issue by gazzatyson** [gitnew2018/My-OpenPeriscope#69]
I followed the instructions to install the chat but when I type npm install in command prompt it just says up to date in 0.031s. The package-lock.json and node_modules folders do not appear.

**Comment by gitnew2018** [comment]
Never happened to me.
Found this https://stackoverflow.com/questions/44493260/npm-install-showing-up-to-date-instead-of-installing-the-packages
I'm not NPM expert, so I might not be able to help you much with this.

You can also download lastest [release](https://github.com/gitnew2018/My-OpenPeriscope/releases/tag/v0.2.07), where chat should work.

**Comment by gazzatyson** [comment]
Chat works now. Thanks.
