### ISSUE TITLE
Bug: OP crashes after broadcast loads

### ISSUE THREAD

**Issue by Alvin388** [gitnew2018/My-OpenPeriscope#7]
Whenever I try opening a broadcast in the OP standalone application, OP crashes exactly when the broadcast has finished loading (Win10).
That problem appeared in older versions of PmmLabs too, but it didn't happen as often.

**Comment by gitnew2018** [comment]
Do you mean that you open periscope webpage by clicking on broadcast title?
If yes then there is not much i can do, it's just a normal browser window(chromium 41), I didn't alter anything there.

**Comment by Alvin388** [comment]
> Do you mean that you open periscope webpage by clicking on broadcast title?
Yes, exactly. Any idea why this could be happening?

**Comment by Alvin388** [comment]
> Do you mean that you open periscope webpage by clicking on broadcast title?

Yes, exactly. Any idea why this could be happening?

**Comment by Alvin388** [comment]
> Doyou mean that you open periscope webpage by clicking on broadcast title?

Yes, exactly. Any idea why this could be happening?

**Comment by gitnew2018** [comment]
Nope, I also hardly ever open them, so i wasn't even aware it does this. I only know that entering chat sometimes crashes the app.

**Comment by ddpk** [comment]
The chat crashes are definitely when its replay chat you're trying to loading, its like 50/50. Speaking of, is there anyway to save chat history to txt automatically? As if you load history and just copy and paste it all?

**Comment by gitnew2018** [comment]
Not really, there is only save as srt button.

**Comment by ddpk** [comment]
I see, SRT isn't that bad. Never tried it before, thanks

**Comment by gitnew2018** [comment]
SRT saves chat messages as subtitles that you can open along with downloaded video.
