### ISSUE TITLE
What is SID?

### ISSUE THREAD

**Issue by OpenPeri1212** [gitnew2018/My-OpenPeriscope#76]
Hey all. Total newbie here. I'm trying to get an authorization token for channel service. The example is saying to enter in the SID in part of the command. Where do I find SID (session ID)? I tried my user ID, the secret and consumer key, and I receive a response of "401 unauthorized". I'm not sure where to locate any other ID. 

(using the x86 windows executable with Windows Subsytem for Linux + Ubuntu for entering the commands found in the example from kewalsk)

Any help is appreciated in locating the session ID.

**Comment by gitnew2018** [comment]
When you **Log in** to periscope.tv in your web browser inspect cookies and find sid there. It should look something like this: ```XysaiiadasklkIjoiMXB6E46sgdDGGDsIlNlc3Npb24iOiJoWnJYOU4xeWRDGd4dgssgs9KS19ZMmtZQTsdgdsgDBTdHJnIi3asWAFFASFSAFaASDDdDafAADSAasfD36I6MX36sdPt-12a2_t1asasdsa35t4ZYj5eMXo2r7VwoOw==```
Or if you're logged in into (my)openperiscope open console then open ```ready!  Object``` and the ```cookie: "```  = SID.

**Comment by OpenPeri1212** [comment]
extremely helpful, @gitnew2018 

Thank you very much
