### ISSUE TITLE
foldernames made more human friendly

### ISSUE THREAD

**Issue by clicksprocket** [gitnew2018/My-OpenPeriscope#79]
Hi

I only discovered this project recently, but love it - very nice job :D 

At the moment (certainly in the standalone version) the default folder naming convention seems to be :-

userID (username)

I find I'm more likely to remember the username, but finding that in a potentially long list is difficult with the current convention. Please may I suggest swapping that around so that it is :- 

username (userID) 

As this would make it easier to find things later.

Thanks again for the great work

**Comment by gizmodo999** [comment]
in the version i use you can edit this yourself.. im not sure if mines standalone or not.. when it loads click the pen icon under your profile pic and it takes you to the settings. click names editor then folder name and you can swap these two around #{user_id}    (#{username})  i have space between mine to make it easier to read.
if you want to make the actual file name a bit easier to read too you can edit this too.. this is how i have mine #{private}#{partial}#{replay}#{day}--#{month}--#{year}-----#{hour}--#{minute}--#{user_display_name}---#{status}     and it comes up like this     26--04--2020-----00--58--NAME---STATUS

**Comment by clicksprocket** [comment]
ooh, thank you - I had no idea those setting were in there - lots of toys to play with :D
