### ISSUE TITLE
Requests: Graphical interface to change file names

### ISSUE THREAD

**Issue by Alvin388** [gitnew2018/My-OpenPeriscope#8]
Would it be in your interest to code a graphical interface that lets you switch file name parameters around without touching the code itself?
My preferred way of naming broadcasts for example would be: 
`username (name) [data_stamp time_stamp] broadcast title cap_type` for files
`username` for folders
Would be amazing to be able to change it all in one line like above in OP settings!

**Comment by gitnew2018** [comment]
Why not, but first I want to make sure that existing features work properly and get it ready for release.

**Comment by DonPepeSun** [comment]
Good idea

**Comment by ronmartins** [comment]
Would love to see this happen

**Comment by Halinks** [comment]
Neat idea! I like it!

**Comment by Halinks** [comment]
Neat idea! I like it!
How about one editable box for folder naming in general, one for public replays, private replays, private lives ,public lives, partial replays etc. 
Then list all parameters down there like: username, broadcast name, timestamp and so on, which you can then copy paste into the box of choice?
I think that would be an easy, modular approach.. no idea if it's hard to implement for you though!

**Comment by Halinks** [comment]
@Max104t Could you maybe help with that one? 🙏

**Comment by gitnew2018** [comment]
Added.

**Comment by Halinks** [comment]
> Added.

Thank you so much!!!

There is one bug I came across though:
When renaming ${private}${partial}${replay} the changes made will not make it into the downloaded file. 
${private} will always be "PV", I can't set it to "PRIV".

Is there a way to change how ${date_created} displays the date? If someone would like to rearrange it or use spaces instead of underscores I mean.

**Comment by gitnew2018** [comment]
Right now there isn't.
