### ISSUE TITLE
Login without twitter

### ISSUE THREAD

**Issue by ghost** [gitnew2018/My-OpenPeriscope#89]
Can we have a way to login without a twitter account? It's easy to make peri accounts but not really easy linking them to a twitter

**Comment by gitnew2018** [comment]
Try logging in with Session id (sid). https://github.com/gitnew2018/My-OpenPeriscope/issues/76

**Comment by ghost** [comment]
> 
> 
> Try logging in with Session id (sid). #76

Best thing I've found out this whole year. I've made so many twitter accounts after making a new gmail for new periscope accounts. Didn't know I could have just been doing it this way all this time lol. Thanks a lot man!
