### ISSUE TITLE
Bug: Doesn't autocap privates

### ISSUE THREAD

**Issue by Alvin388** [gitnew2018/My-OpenPeriscope#9]
I tried everything. Even without any edits to the code from me, the 0.1.5 version and onward does not auto download privates.
Does it work for you guys?

**Comment by gitnew2018** [comment]
Cannot confirm. What are your settings?

**Comment by Alvin388** [comment]
✅ Enable auto downloading for:
    ✅ Private broadcasts
    ✅ Selected user broadcasts

Notification refresh interval: 15 secs
Download Path valid

✅Auto update thumbnails
✅Show M3U links
✅Show PR links

Tested by four people on several different computers... OP just won't auto capture anything.
